name: CI - Django & Angular

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # FRONTEND
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: App-Frontend/Frontend/package-lock.json

      - name: Install Frontend dependencies
        working-directory: App-Frontend/Frontend
        run: npm install

      - name: Build Angular
        working-directory: App-Frontend/Frontend
        run: npm run build --if-present

      # BACKEND (FIXED PY VERSION)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Backend dependencies
        working-directory: App-Backend/backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Django migrate
        working-directory: App-Backend/backend
        run: python manage.py migrate

      - name: Django tests
        working-directory: App-Backend/backend
        run: python manage.py test
